#*********************************************************************
#
#  (C) 2001 Web3d Consortium
#    http://www.web3d.org/
#
# Package makefile for the org.web3d.vrml.renderer.norender.nodes.networking
# directory
#
# Author: Justin Couch
# Version: $Revision: 1.6 $
#
#*********************************************************************

PACKAGE = org.web3d.vrml.renderer.norender.nodes.dis

# The source files to compile. These are declared in order that they must be
# compiled in
SOURCE = NREspduTransform.java \
  NRDISEntityManager.java \

# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA =

# If the package requires extra classes outside the JDK, the JAR files that
# are required are listed here. These should be found in ${PROJECT_ROOT}/lib
JARS_3RDPARTY = jaxb-api.jar dis-enums.jar hibernate-jpa-2.0-api-1.0.0.Final.jar open-dis_4.06.jar

include ${PROJECT_ROOT}/make/Makefile.jav